import java.util.ArrayList;

// Generated by Class Director
public class ListOfClassRequirements{

	private ArrayList<Class> listOfClassRequirements = new ArrayList<>();

	public ListOfClassRequirements(){
	}

	public ArrayList<Class> getListOfClassRequirements(){
		return this.listOfClassRequirements;
	}

	void add(Class newRequirement) {
		this.listOfClassRequirements.add(newRequirement);
	}

	void remove(Class subRequirement){
		this.listOfClassRequirements.remove(subRequirement);
		subRequirement.destroy();
	}

	int requirementsRemaining(){
		return this.listOfClassRequirements.size();
	}

	boolean reqirementsMet(){
		if(this.requirementsRemaining() == 0){
			return true;
		}
		return false;
	}

	public String find(String search){
		for(Class curVal : listOfClassRequirements){
			if(curVal.getName().contains(search)){
				return curVal.print();
			}
			if(curVal.getSubjectArea().contains(search)){
				return curVal.print();
			}
			if(curVal.getSchedule().contains(search)){
				return curVal.print();
			}
		}
		return "Your search has returned empty...";
	}

	public void print(){
		for(Class printVal : listOfClassRequirements){
			System.out.print(printVal.print() + "\n");
		}
	}
}